version: '3.8'
services:
  api:
    container_name: main_api_service
    build: .
    ports:
      - "3030:3030"
    volumes:
      - .:/api/
      - /api/node_modules
    environment:
      NODE_ENV: development
